In [7]:
#!/bin/python3
import pandas as pd
import numpy as np
from pandas_datareader import data
!pip install yfinance==0.2.28
import yfinance as yf
yf.pdr_override()
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


def load_financial_data(start_date, end_date,output_file):
    try:
        df = pd.read_pickle(output_file)
        print('File data found...reading GOOG data')
    except FileNotFoundError:
        print('File not found...downloading the GOOG data')
        df = data.DataReader('GOOG', start_date, end_date)
        df.to_pickle(output_file)
    return df

goog_data=load_financial_data(start_date='2001-01-01',
                    end_date = '2018-01-01',
                    output_file='goog_data.pkl')

Collecting yfinance==0.2.28
  Downloading yfinance-0.2.28-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 799 kB/s eta 0:00:011
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (1.22.4)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (2.0.3)
Requirement already satisfied: html5lib>=1.1 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (1.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (4.12.2)
Requirement already satisfied: appdirs>=1.4.4 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (1.4.4)
Requirement already satisfied: lxml>=4.9.1 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (4.9.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (2.31.0)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (2.3.8)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (2023.3.post1)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.8/site-packages (from yfinance==0.2.28) (0.0.11)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.8/site-packages (from beautifulsoup4>=4.11.1->yfinance==0.2.28) (2.2.1)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.8/site-packages (from html5lib>=1.1->yfinance==0.2.28) (0.5.1)
Requirement already satisfied: six>=1.9 in /opt/anaconda3/lib/python3.8/site-packages (from html5lib>=1.1->yfinance==0.2.28) (1.15.0)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.3.0->yfinance==0.2.28) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.3.0->yfinance==0.2.28) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance==0.2.28) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance==0.2.28) (2.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance==0.2.28) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance==0.2.28) (1.26.4)
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.29
    Uninstalling yfinance-0.2.29:
      Successfully uninstalled yfinance-0.2.29
Successfully installed yfinance-0.2.28
File data found...reading GOOG data

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_pickle('/Users/yiningqu/Desktop/goog_data.pkl')
df

                 Open       High        Low      Close  Adj Close     Volume
Date
2004-08-19   2.490664   2.591785   2.390042   2.499133   2.499133  897427216
2004-08-20   2.515820   2.716817   2.503118   2.697639   2.697639  458857488
2004-08-23   2.758411   2.826406   2.716070   2.724787   2.724787  366857939
2004-08-24   2.770615   2.779581   2.579581   2.611960   2.611960  306396159
2004-08-25   2.614201   2.689918   2.587302   2.640104   2.640104  184645512
...               ...        ...        ...        ...        ...        ...
2017-12-22  53.055500  53.209999  52.972000  53.006001  53.006001   15102000
2017-12-26  52.903500  53.006001  52.509998  52.837002  52.837002   15212000
2017-12-27  52.869499  52.918499  52.402500  52.468498  52.468498   25438000
2017-12-28  52.580002  52.737499  52.238499  52.407001  52.407001   16742000
2017-12-29  52.335999  52.485001  52.244999  52.320000  52.320000   17750000

[3366 rows x 6 columns]

In [ ]:
def random_data(financial_data):
    signals = pd.DataFrame(index=financial_data.shape[0])
    data = np.random.randin(0,2)